services:
  web:
    build: ./
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn project.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 5432
    volumes:
      - ./:/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  celery:
    build: ./
    command: celery -A sporthack worker -B -l info
    depends_on:
      - redis
    ports:
      - 5432
  celery-beat:
    build: ./
    command: celery -A sporthack beat -l info
    depends_on:
      - redis
    ports:
      - 5432
  redis:
    image: redis:alpine
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/web/staticfiles
      - media_volume:/app/web/mediafiles

volumes:
  static_volume:
  media_volume:  