services:
  web:
    build: ./
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "5433:5432"
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"